#!/bin/bash


# Help output

if [[ $# -lt 1 ]] || [[ $1 != *.desktop ]]; then
    echo "Usage: $0 <desktop entry>"
    exit
fi


# Check if PRIME is supported and correctly set up

if ! [[ -f /var/lib/ubuntu-drivers-common/last_gfx_boot ]]; then
    kdialog --yesno "/var/lib/ubuntu-drivers-common/last_gfx_boot not found. Can't find number of installed GPUs.\n\nContinue anyway?"
    if ! [[ $? ]]; then exit; fi
else
    GPU_COUNT=$(wc -l /var/lib/ubuntu-drivers-common/last_gfx_boot | awk '{print $1}')

    if [[ $GPU_COUNT -lt 1 ]]; then
        kdialog --yesno "/var/lib/ubuntu-drivers-common/last_gfx_boot empty. Can't find number of installed GPUs.\n\nContinue anyway?"
        if ! [[ $? ]]; then exit; fi
    elif [[ $GPU_COUNT -eq 1 ]]; then
        kdialog --yesno "System does not support GPU offloading. It either has only one GPU or one of the GPUs is disabled in BIOS.\n\nContinue anyway?"
        if ! [[ $? ]]; then exit; fi
    fi
fi

if ! command -v prime-select > /dev/null 2>&1; then
    kdialog --yesno "prime-select not found. GPU offloading not installed correctly.\n\nContinue anyway?"
    if ! $?; then exit; fi
else
    if [[ $(prime-select query) != "on-demand" ]]; then
        kdialog --yesno "GPU on-demand mode not active. Run \"sudo prime-select on-demand\" and reboot your system to correct this setting.\n\nContinue anyway?"
        if ! [[ $? ]]; then exit; fi
    fi
fi


# Check if desktop entry is an unsuported launcher shortcut

EXEC_LINE=$(awk -F '=' '
    $0~"^\\s*\\[Desktop Entry\\]\\s*$" {
        SECTION_ACTIVE=1
        next
    }
    $0~"^\\s*\\[.*\\]\\s*$" {
        SECTION_ACTIVE=0
        next
    }
    SECTION_ACTIVE==1 && $1~"^\\s*Exec\\s*$" {
        print $0
    }
' "$1" | sed 's/\s*Exec\s*=//')

if [[ $EXEC_LINE =~ steam[[:space:]]*steam://rungameid/ ]]; then
    kdialog "Steam shortcuts are not supported by this command. To enable GPU offloading for Steam apps follow this guide instead <link>."
    exit
fi

if [[ $EXEC_LINE =~ lutris[[:space:]]*lutris:rungameid/ ]]; then
    kdialog "Lutris shortcuts are not supported by this command. To enable GPU offloading for Lutris apps follow this guide instead <link>."
    exit
fi

if [[ $EXEC_LINE =~ rare[[:space:]]*launch[[:space:]]* ]]; then
    kdialog "Rare shortcuts are not supported by this command. To enable GPU offloading for Rare apps follow this guide instead <link>."
    exit
fi

# Minigalaxy and Heroic don't create shortcuts
# To check:
# itch.io
# GameHub
# Bottles
# PlayOnLinux
# Pegasus Frontend
# Epic Games Store installed through Lutris
# UbisoftConnect installed through Lutris
# Origin installed through Lutris


# Activate offloading using environment variables

# Vulkan: Activate implicit overlay for offloading (which reordes available GPUs so that dGPUs come first)
# OpenGL: Make NVIDIAs implementation checking if it is running on an optimus device (and therefore making it not crash on optimus devices)
export __NV_PRIME_RENDER_OFFLOAD=1
# Vulkan: Make implicit overlay for offloading remove all non NVIDIA GPUs from the availability list (optional)
export __VK_LAYER_NV_optimus=NVIDIA_only
# OpenGL: Use NVIDIAs OpenGL implementation (aka using the propriatary NVIDIA driver and not Mesa which only supports the opten source driver e.g. i915, amdgpu, and nouveau)
export __GLX_VENDOR_LIBRARY_NAME=nvidia


# Run the desktop entry

kioclient exec $1
